[package]
name = "rust_examples"
version = "0.1.0"
authors = ["ypyf <t34@qq.com>"]

[dependencies]
num = "0.1.32"

[[bin]]
name = "lifetime"
path = "src/lifetime.rs"

[[bin]]
name = "concurrency"
path = "src/concurrency.rs"
